// Example
export const INCREASE_NUMBER = 'INCREASE_NUMBER'

export const GET_GITHUB_API = 'GET_GITHUB_API'
export const GET_GITHUB_API_SUCCESS = 'GET_GITHUB_API_SUCCESS'
export const GET_GITHUB_API_FAIL = 'GET_GITHUB_API_FAIL'
